name: Cypress Tests with Allure Report

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    env:
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      CYPRESS_CACHE_FOLDER: ~/.cache/Cypress

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
      
      - name: Install Allure Report
        run: |
          npm install --save-dev mocha-allure-reporter allure-commandline
          mkdir -p allure-results

      - name: Run Cypress Tests
        run: |
          npx cypress run

          - name: Generate Allure Report
          run: |
            allure generate allure-results --clean -o allure-report
            allure open allure-report
  
      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v3
        with:
            name: allure-report
            path: allure-report
  
      - name: Publish Allure Report to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: allure-report
            publish_branch: gh-pages