name: Cypress Tests

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci

  eslint:
    needs: install_dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npx eslint 'cypress/**/*.js' '*.js'

  cypress-tests:
    needs: eslint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { name: desktop, width: 1280, height: 720, browser: chrome }
          - { name: ipad, width: 768, height: 1024, browser: chrome }
          - { name: iphone, width: 375, height: 667, browser: chrome }
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run Cypress Tests for ${{ matrix.config.name }} on ${{ matrix.config.browser }}
        run: |
          npx cypress run --browser ${{ matrix.config.browser }} --config viewportWidth=${{ matrix.config.width }},viewportHeight=${{ matrix.config.height }}
      - name: Upload Cypress Artifacts
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts-${{ matrix.config.name }}
          path: |
            cypress/screenshots
            cypress/videos